name: flutter_hive_json
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0-19.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_annotation : ^4.0.1
  provider: ^6.0.2 
  http: ^0.13.4
  hive_flutter: ^1.1.0
  # shared_preferences: ^2.0.13

  

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  hive_generator: ^1.1.0
  analyzer: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/logo.jpg
  #   - assets/images/atidstu_logo.gif

  # example:
  # fonts:
  #   - family: JetBrainsMono
  #     fonts:
  #       - asset: assets/fonts/JetBrainsMono-Bold.ttf
  #       - asset: assets/fonts/JetBrainsMono-Medium.ttf
  #       - asset: assets/fonts/JetBrainsMonoNL-Medium.ttf
  #   - family: FiraCode
  #     fonts:
  #       - asset: assets/fonts/FiraCode-Medium.ttf
